### ISSUE TITLE
Issues with ft6x36

### ISSUE THREAD

**Issue by rphughespa** [lemariva/micropython-core2#8]
I am trying to run the example code and I am getting errors related to ft6x36.

I loaded the firmware,  lv_micropython_m5core2_bf62dfc784_esp32_idf4_4_x.bin,
using the esptool.  I then loaded the examples boot.py, buttons.py as main.py and config.py.

The hardware is the core2 for aws iot.

Below are the messages get  when i try to run the buttons example. 

Am I missing something?

thanks,
richard

===============

MPY: soft reboot
Booting
connecting to network...
network config: ('192.168.1.31', '255.255.255.0', '192.168.1.1', '192.168.1.1')
AXP192 I2C connection [OK].
AXP192 I2C connection [OK].
Single buffer
ILI9341 initialization completed
Enable backlight
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "ft6x36.py", line 36, in __init__
ValueError: FT6336U I2C connection [FAIL].

MicroPython v1.18-599-gbf62dfc78-dirty on 2022-02-02; M5Stack Core2 with ESP32

**Comment by jr-air** [comment]
Am having the exact same issue. I was able to determine where the rror was source from, but not sure how to fix. 

Were you able to figure out this issue?

Line 70 from machine_ft6336u.c.
